---
# Changing these may throw off the placement of the text
"window_width": 640
"window_height": 480
"tile_width": 20

# Colors: black, gray, white, aqua, red,
#         green, blue, yellow, fuchsia, cyan
"map_color": green
"border_color": red
"text_color": black

"rabbit_color": white
"player1_snake_color": black
"player2_snake_color": gray

"game_speed": 100

"snake_start_size": 5
"snake_grow_length": 5

"rabbit_hop_distance": 5
"num_of_rabbits": 5

"two_player": true
# "two_player": false


